
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

import math

print(sum([int((((1 + math.sqrt(5)) / 2)**i - ((1 - math.sqrt(5)) / 2)**i) / math.sqrt(5)) if int((((1 + math.sqrt(5)) / 2)**i - ((1 - math.sqrt(5)) / 2)**i) / math.sqrt(5)) % 2 == 0 else 0 for i in range(34)]))
